version: "3.8"

services:
  frontend:
    build:
      context: ./frontend  # Ensure the correct path
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Ensure the correct path
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
